version: '3.8'

services:
  fastapi-app:
    image: jisoo708/fastapi-app:latest
    container_name: fastapi-container
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - /home/ubuntu/Server/.env:/Server/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
