name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: FastAPI 실행 가능 여부 확인
        run: uvicorn --help

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Docker 로그인
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker 이미지 빌드 및 푸시
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: 서버에 환경 변수 파일 업로드
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Server  # EC2 내 프로젝트 디렉토리로 이동
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "GPT_API_KEY=${{ secrets.GPT_API_KEY }}" >> .env
            echo "ENV=prod" >> .env

      - name: 서버에서 Docker Compose로 배포 실행
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Server
            docker-compose pull
            docker-compose up --pull always --force-recreate -d

            # 실행 확인을 위해 로그 출력
            sleep 5
            sudo docker-compose logs fastapi-app
